# Editorial beat sheet for the "Black Holes" documentary transcript.
# Timestamps are derived automatically from cumulative word count at
# ~150 words/minute (typical calm documentary narration pace).

BEATS = [
    # -- COLD OPEN / HOOK --
    dict(text="Somewhere out there right now is a point in space where gravity has completely broken the rules.",
         visual="Slow push-in on a deep starfield / nebula — ominous cosmic establishing shot",
         type="Video", keywords=["deep space nebula", "stars slow motion", "galaxy zoom"],
         notes="Sets the mythic, ominous tone of the cold open. Slow push-in, hold ~6-7s."),
    dict(text="Light can't escape it.",
         visual="Pure black void / dark space texture, light seeming to vanish",
         type="Image", keywords=["black hole illustration", "dark space"],
         notes="Quick punch cut, 2-3s, reinforces the sentence literally."),
    dict(text="Time bends around it.",
         visual="Abstract gravitational lensing / warped light illustration",
         type="Image", keywords=["gravitational lensing", "space time warp"],
         notes="2-3s, abstract visual metaphor for spacetime distortion."),
    dict(text="And if you got too close, your body would be torn apart, atom by atom.",
         visual="Swirling accretion disk / cosmic vortex animation",
         type="Video", keywords=["black hole accretion disk", "space vortex animation"],
         notes="~5s, dramatic swirling motion sells the danger."),
    dict(text="So what is a black hole, actually?",
         visual="Observatory telescope pointed at night sky (title-card beat)",
         type="Video", keywords=["telescope night sky", "observatory stars"],
         notes="3-4s transition beat into the explainer section."),

    # -- HOW STARS DIE --
    dict(text="To understand that, we have to start with how stars die.",
         visual="Wide Milky Way / starfield establishing shot",
         type="Video", keywords=["milky way timelapse", "night sky stars"],
         notes="4s, resets scene for the new chapter."),
    dict(text="Every star is basically a battle.",
         visual="Close-up of the sun's surface / solar flare",
         type="Video", keywords=["sun surface close up", "solar flare"],
         notes="3s, introduces the 'battle' metaphor visually."),
    dict(text="In its core, hydrogen atoms are being crushed together so hard they fuse into helium,",
         visual="Abstract particle/atom collision science visualization",
         type="Image", keywords=["hydrogen atom illustration", "nuclear fusion science"],
         notes="4-5s, symbolic since literal fusion footage doesn't exist on stock sites."),
    dict(text="and that fusion releases a massive outward push of energy.",
         visual="Solar flare eruption bursting outward",
         type="Video", keywords=["solar flare eruption", "sun energy burst"],
         notes="4s, energetic payoff shot right after the fusion beat."),
    dict(text="That push fights against the star's own gravity, which is constantly trying to crush it inward.",
         visual="Pulsing plasma surface of a star, close-up",
         type="Video", keywords=["sun plasma close up", "star surface texture"],
         notes="5s, continuous motion visualizes the constant 'fight'."),
    dict(text="For most of a star's life, these two forces are in a standoff.",
         visual="Calm, stable star / sun timelapse",
         type="Video", keywords=["sun timelapse space", "star calm space"],
         notes="4s, calmer pacing before the escalation in the next section."),

    # -- MASSIVE STARS / IRON --
    dict(text="But really massive stars — ones many times heavier than our sun — don't stop at helium.",
         visual="Red supergiant / giant star size comparison image",
         type="Image", keywords=["red supergiant star", "giant star space"],
         notes="5s, visually communicates scale of 'really massive stars'."),
    dict(text="They keep fusing heavier and heavier elements, all the way up to iron.",
         visual="Macro shot of raw iron / metal texture",
         type="Image", keywords=["iron metal texture", "raw metal macro"],
         notes="4s, literal/symbolic close-up of iron itself."),
    dict(text="And iron is where the whole system breaks.",
         visual="Metal or glass cracking/shattering, slow motion",
         type="Video", keywords=["glass shattering slow motion", "metal cracking"],
         notes="3-4s, metaphor for the system 'breaking'."),
    dict(text="Fusing iron doesn't release energy, it costs energy.",
         visual="A star dimming / fading light in space",
         type="Image", keywords=["dying star fading", "dim star space"],
         notes="4s, visual dimming reinforces 'costs energy'."),
    dict(text="So once a star's core turns to iron, there's nothing left pushing back against gravity.",
         visual="Star collapsing inward, animated simulation",
         type="Video", keywords=["star collapse animation", "space implosion"],
         notes="5s, sets up the imminent collapse."),

    # -- CORE COLLAPSE / SUPERNOVA --
    dict(text="The core collapses in less than a second.",
         visual="Fast implosion / rapid zoom animation",
         type="Video", keywords=["implosion animation", "space collapse fast"],
         notes="Quick 3s cut — pacing should feel abrupt, matching 'less than a second'."),
    dict(text="We're talking material falling inward at a quarter of the speed of light.",
         visual="Streaking light / warp-speed motion effect",
         type="Video", keywords=["light speed warp", "space motion streaks"],
         notes="4s, conveys extreme velocity."),
    dict(text="The rest of the star slams into that collapsing core and rebounds outward",
         visual="Explosive shockwave bursting outward in space",
         type="Video", keywords=["explosion shockwave space", "energy blast animation"],
         notes="4-5s, kinetic build-up to the supernova payoff."),
    dict(text="in one of the most violent events in the universe: a supernova.",
         visual="Full supernova explosion — bright nebula burst",
         type="Video", keywords=["supernova explosion", "nebula explosion space"],
         notes="6-7s — the biggest visual payoff so far, let it breathe longer than surrounding beats."),
    dict(text="It's actually inside that explosion that most of the heavy elements in the universe get forged",
         visual="Colorful gas cloud / nebula with rich color detail",
         type="Image", keywords=["colorful nebula", "gas cloud space"],
         notes="5s, colorful nebula stands in for 'elements being forged'."),
    dict(text="including, probably, some of the atoms in your own body.",
         visual="Silhouette of a person under a starry night sky",
         type="Image", keywords=["silhouette person starry sky", "person night sky stars"],
         notes="4-5s, emotional 'we are stardust' beat — bring it back to a human scale."),

    # -- NEUTRON STAR / BLACK HOLE FORMS --
    dict(text="What's left behind depends on how much mass survives.",
         visual="Supernova remnant / expanding nebula shell",
         type="Image", keywords=["supernova remnant nebula", "nebula shell space"],
         notes="4s, aftermath imagery."),
    dict(text="Sometimes it's a neutron star, insanely dense but still technically a star.",
         visual="Neutron star / pulsar illustration",
         type="Image", keywords=["neutron star illustration", "pulsar space"],
         notes="5s, distinct visual identity from the black hole imagery to come."),
    dict(text="But if enough mass remains, gravity wins completely, and the core doesn't just get dense — it collapses forever.",
         visual="Gravitational collapse into darkness, animated",
         type="Video", keywords=["black hole formation animation", "gravity collapse space"],
         notes="6s, visualizes the actual formation moment."),
    dict(text="That's a black hole.",
         visual="Black hole with glowing event horizon (hero shot)",
         type="Image", keywords=["black hole space illustration", "event horizon image"],
         notes="3s punch beat — first clean 'reveal' of the subject."),

    # -- WHAT IT LOOKS LIKE --
    dict(text="Now here's where it gets strange.",
         visual="Abstract swirling space transition",
         type="Video", keywords=["abstract space swirl", "space transition motion"],
         notes="3s connective tissue beat before the deep-dive."),
    dict(text="If you could actually look at a black hole, you wouldn't be looking at a hole at all.",
         visual="Event Horizon Telescope–style black hole image (glowing ring, dark center)",
         type="Image", keywords=["black hole event horizon", "black hole ring image"],
         notes="5-6s, the most iconic and recognizable black hole image style."),
    dict(text="What you'd see is the event horizon — an invisible boundary in space, not a physical surface.",
         visual="Accretion disk simulation, glowing ring around darkness",
         type="Video", keywords=["black hole accretion disk animation", "space ring glow"],
         notes="5s, motion sells 'boundary' better than a still."),
    dict(text="Cross it, and to get back out you'd need to travel faster than light.",
         visual="Light streaks bending around a dark sphere",
         type="Video", keywords=["light bending gravity", "light trails space animation"],
         notes="4s."),
    dict(text="Since nothing can do that, the event horizon is a one-way door.",
         visual="Dark tunnel / threshold, one-directional motion",
         type="Image", keywords=["dark tunnel space", "one way threshold abstract"],
         notes="4s, symbolic 'one-way door' framing."),
    dict(text="That's why it looks pitch black: it's not a dark object floating there, it's that literally no light escapes to reach your eyes.",
         visual="Pure black void / deep space darkness close-up",
         type="Image", keywords=["black void space", "dark space texture"],
         notes="5-6s, let the darkness itself be the visual."),

    # -- SINGULARITY --
    dict(text="So if the black part is the event horizon, what's actually inside?",
         visual="Slow zoom into the center of a black hole graphic",
         type="Video", keywords=["black hole zoom animation", "space hole zoom"],
         notes="4s, builds curiosity heading into the singularity beat."),
    dict(text="That's the singularity, and honestly, we don't fully know what it is.",
         visual="Single intense point of bright light against black background",
         type="Image", keywords=["bright point light abstract", "single light point dark background"],
         notes="4-5s, minimalist visual for an infinitely small point."),
    dict(text="Our best equations say all the mass of the collapsed star gets crushed into an infinitely small point with no size at all.",
         visual="Physics equations on a chalkboard or screen",
         type="Image", keywords=["physics equations chalkboard", "science formula blackboard"],
         notes="6s, classic 'science' visual shorthand."),
    dict(text="When physicists run the math, it basically breaks — the same way a calculator breaks if you try to divide by zero.",
         visual="Close-up of a calculator display / numbers",
         type="Image", keywords=["calculator close up", "numbers display close up"],
         notes="5s, literal and slightly playful — good for viewer engagement."),

    # -- MYTH BUSTING --
    dict(text="And here's a myth worth killing right now: black holes do not suck things in like some cosmic vacuum cleaner.",
         visual="Household vacuum cleaner in use (tongue-in-cheek cutaway)",
         type="Image", keywords=["vacuum cleaner household", "vacuum cleaner cleaning"],
         notes="4-5s, Vox-style humorous literal cutaway for the 'vacuum cleaner' line."),
    dict(text="Their gravity works exactly like any other object's gravity — it depends on mass and distance, nothing more.",
         visual="Planets orbiting in stable paths / orbital diagram",
         type="Image", keywords=["planet orbit diagram", "solar system orbit illustration"],
         notes="5s, reinforces 'normal gravity' with an ordinary orbital visual."),
    dict(text="If you swapped our sun for a black hole of the exact same mass tomorrow, Earth's orbit wouldn't change at all.",
         visual="Earth orbiting the sun, animated",
         type="Video", keywords=["earth orbit sun animation", "earth space orbit"],
         notes="5-6s, direct visualization of the thought experiment."),
    dict(text="We'd just freeze, since there'd be no sunlight anymore.",
         visual="Frozen, icy landscape",
         type="Video", keywords=["frozen ice landscape", "snow ice cold nature"],
         notes="4s, grounds the abstract idea in a relatable frozen-Earth image."),
    dict(text="You'd only get pulled in if you got dangerously close to the event horizon itself.",
         visual="Object/debris being drawn toward a black hole, simulation",
         type="Video", keywords=["black hole gravity pull", "space debris falling animation"],
         notes="4-5s, returns focus to the black hole itself."),

    # -- FALLING IN / RELATIVITY --
    dict(text="So what would actually happen to you if you fell in? It depends who's watching.",
         visual="Astronaut floating/falling in space",
         type="Video", keywords=["astronaut floating space", "astronaut weightless space"],
         notes="5s, introduces the human thought experiment."),
    dict(text="From the outside, your friends would see you slow down more and more as you approached the event horizon,",
         visual="Astronaut drifting in slow motion",
         type="Video", keywords=["astronaut slow motion space", "astronaut drifting space"],
         notes="5s, slowed motion literally matches the narration."),
    dict(text="fading and redshifting, until you appeared frozen in place forever.",
         visual="Red-tinted glow / fading light abstract effect",
         type="Image", keywords=["red glow abstract light", "fading red light effect"],
         notes="4-5s, color cues the 'redshifting' concept directly."),
    dict(text="But from your own point of view, time would feel completely normal",
         visual="Calm astronaut spacewalk, first-person feel",
         type="Video", keywords=["astronaut spacewalk calm", "astronaut space walk"],
         notes="4s, contrast in pacing/calm to sell the subjective normalcy."),
    dict(text="you'd just watch the rest of the universe race ahead of you, like the whole future playing in fast forward.",
         visual="Star trails / night sky timelapse streaking",
         type="Video", keywords=["star trails timelapse", "night sky star trails motion"],
         notes="5-6s, star-trail timelapse is a perfect visual metaphor for 'fast forward'."),

    # -- SPAGHETTIFICATION / FIREWALL --
    dict(text="As for what happens after you cross the horizon, physicists genuinely disagree.",
         visual="Scientist at a chalkboard, thinking",
         type="Image", keywords=["scientist chalkboard thinking", "physics research chalkboard"],
         notes="4s, signals a shift to competing theories."),
    dict(text="One idea says you'd be stretched — spaghettified — as gravity pulls harder on your feet than your head, until you're a thread of atoms one particle wide.",
         visual="Abstract stretching/elastic light trail effect, slow motion",
         type="Video", keywords=["stretching light trail abstract", "elastic motion slow"],
         notes="6s, symbolic stand-in since literal 'spaghettification' footage doesn't exist."),
    dict(text="Another idea, called the firewall theory, says you'd hit a wall of high-energy radiation right at the boundary and be destroyed instantly, before spaghettification even gets the chance.",
         visual="Bright plasma/fire energy burst wall",
         type="Video", keywords=["plasma energy burst", "fire wall explosion effect"],
         notes="5-6s, high-energy visual matches 'firewall' literally."),
    dict(text="Nobody's proven which one is correct, and nobody's exactly lining up to test it.",
         visual="Telescope scanning the night sky",
         type="Video", keywords=["telescope scanning sky", "observatory night sky"],
         notes="4-5s, wry, lighter beat before the next factual section."),

    # -- TYPES OF BLACK HOLES --
    dict(text="Not all black holes are created equal, either.",
         visual="Starfield transition shot",
         type="Video", keywords=["stars background transition", "space background motion"],
         notes="3s connective beat."),
    dict(text="Stellar black holes, formed the way we just described, are usually only a few times heavier than our sun, packed into a space smaller than a city.",
         visual="Aerial night skyline of a city (scale comparison)",
         type="Video", keywords=["city aerial night skyline", "city lights aerial view"],
         notes="5-6s, gives the viewer a tangible scale reference."),
    dict(text="But at the center of nearly every galaxy sits something far bigger: a supermassive black hole.",
         visual="Spiral galaxy with bright glowing core",
         type="Image", keywords=["spiral galaxy core", "galaxy bright center"],
         notes="5s."),
    dict(text="Our own galaxy's central black hole, Sagittarius A*, is about four million times the mass of the sun.",
         visual="Milky Way galactic center image",
         type="Image", keywords=["milky way galactic center", "milky way core stars"],
         notes="5-6s, ties back to our own galaxy specifically."),
    dict(text="That sounds enormous, until you compare it to TON 618, one of the largest black holes ever found",
         visual="Bright distant quasar / active galaxy image",
         type="Image", keywords=["quasar bright galaxy", "distant galaxy space image"],
         notes="5s, sets up the scale comparison."),
    dict(text="an estimated 66 billion solar masses, with an event horizon wider than our entire solar system.",
         visual="Solar system scale illustration",
         type="Image", keywords=["solar system illustration", "planets scale diagram"],
         notes="5-6s, visual scale payoff for the comparison."),

    # -- HAWKING RADIATION --
    dict(text="Given enough time, even something that powerful eventually dies.",
         visual="Star or light source slowly fading to black",
         type="Video", keywords=["fading light slow motion", "star fading dark space"],
         notes="4s."),
    dict(text="Stephen Hawking showed that black holes very slowly leak energy through a process now called Hawking radiation.",
         visual="Physics equations / blackboard science visual",
         type="Image", keywords=["physics equations blackboard", "science formula chalkboard"],
         notes="5-6s, kept symbolic/chalkboard rather than attempting a lookalike photo."),
    dict(text="Right at the edge of the event horizon, pairs of particles are constantly popping in and out of existence.",
         visual="Quantum particle / energy spark animation",
         type="Video", keywords=["quantum particle animation", "energy particle spark motion"],
         notes="5s."),
    dict(text="Occasionally one particle falls in while its partner escapes, and that escaping particle carries away a tiny bit of the black hole's mass.",
         visual="Particle splitting/separating animation, one streak departing",
         type="Video", keywords=["particle split animation", "light particle separating motion"],
         notes="5-6s."),
    dict(text="Over time, that adds up.",
         visual="Hourglass / sand timer close-up",
         type="Image", keywords=["hourglass sand timer", "sand time close up"],
         notes="3s, simple symbolic beat for accumulation over time."),

    # -- TIMESCALE / HEAT DEATH --
    dict(text="The catch is the timescale.",
         visual="Clock or watch mechanism close-up",
         type="Image", keywords=["clock close up", "watch mechanism macro"],
         notes="3s."),
    dict(text="A supermassive black hole could take longer than a googol years to fully evaporate — that's a one followed by a hundred zeros.",
         visual="Abstract digital numbers / data visualization",
         type="Image", keywords=["digital numbers abstract", "data numbers background"],
         notes="5-6s, communicates 'incomprehensibly large number' visually."),
    dict(text="The universe as we know it will almost certainly be unrecognizable, if it exists at all, long before the last black hole finally blinks out.",
         visual="Vast, empty deep space — dark and sparse",
         type="Video", keywords=["deep space empty vast", "dark space vast emptiness"],
         notes="6-7s, conveys cosmic-scale desolation; let it linger."),

    # -- OUTRO --
    dict(text="Black holes might be the closest thing we have to actual magic in physics — objects so extreme they break our best equations.",
         visual="Dramatic black hole hero shot (callback to the opening)",
         type="Image", keywords=["black hole space art", "black hole illustration dramatic"],
         notes="5-6s, deliberate visual callback to the cold open for a satisfying bookend."),
    dict(text="If this helped you actually understand them, hit like, and subscribe for more videos that make space make sense.",
         visual="Slow pan across a starry night sky",
         type="Video", keywords=["night sky stars pan", "starry sky camera pan"],
         notes="5-6s outro CTA beat, calm visual leaves room for on-screen subscribe graphics."),
]
